### PR TITLE
added eslint with airbnb styling

### PR DESCRIPTION
**Pull request by urrri**
added npm script to run eslint.

### CODE REVIEW

**Comment by assafg** [comment]
Part of this commit is to have the lint pass (fix the errors)
npm run lint produces 231 problems...

**Comment by urrri** [comment]
That's cool. First you complain that I write non-airbnb and asks to add linting for it and then it turns out that all your project full of airbnb errors.

**Comment by assafg** [comment]
Firs of all I don't appreciate your tone.
I commented on your pull request that it is not the correct style for the
project. I added a task for adding lint to the project to keep it in form.
If you add lint to to the project it is expected that you have the entire
project pass that lint, otherwise - what's the point?!
If it's too dificult for you to fix leave it as is.

**Comment by urrri** [comment]
1.There is no tone in writing. If you fill something - sorry.
2.You commented that you used airbnb styling for project.
3.adding lint means add task and tools to allow linting. Then according to policy (regularly everyone fixes own code)
4.it isnt difficult. it is tedious and dirty work

**Comment by assafg** [comment]
1. I have no time for sarcastic remarks.
2. That's not true. I said I use 2 spaces per tab and I think the airbnb
style is popular and would be nice to have.
3. It is optimal to add lint at project startup but if not- then adding
lint requires backwards fixing.
4. I know :( but someone needs to do it...

On 12 Sep 2016 17:36, "Yury Goltsman" <notifications@github.com> wrote:

1.There is no tone in writing. If you fill something - sorry.
2.You commented that you used airbnb styling for project.
3.adding lint means add task and tools to allow linting. Then according to
policy (regularly everyone fixes own code)
4.it isnt difficult. it is tedious and dirty work

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tikalk/hr-emplyee-profile-manager/pull/12#issuecomment-246367641>,
or mute the thread

**Comment by urrri** [comment]
2."I currently adhere to the popular AirBNB style-guide" & "If you contribute
code to a project you should be consistent"
I understood from these citations that you used AirBNB styling in the project.

**Pull request merged**
